# Generated by Django 3.2.9 on 2021-11-05 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('descripcion', models.CharField(help_text='Descripción de la Categoría', max_length=100, unique=True, verbose_name='Descripción')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_crea', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modifica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['fc'],
            },
        ),
    ]
