# Generated by Django 3.2.9 on 2021-11-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_alter_categoria_um'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='um',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
