# Generated by Django 3.2.9 on 2021-11-05 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0003_alter_categoria_um'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la SubCategoría', max_length=100, verbose_name='SubDescripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.categoria')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubCategoría',
                'verbose_name_plural': 'SubCategorías',
                'ordering': ['fc'],
                'unique_together': {('categoria', 'descripcion')},
            },
        ),
    ]
